export const accessories = [
  {
    id: 17,
    name: 'iPhone guminis dėklas "Fundamental"',
    price: "€8.00",
    stock: 3,
    color: "black",
    descriptions: [
      "Lankstus, guminis dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone1.jpg",
  },
  {
    id: 18,
    name: 'iPhone kietas dėklas "Fundamental"',
    price: "€9.00",
    stock: 2,
    color: "black",
    descriptions: [
      "Kietas dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone2.jpg",
  },
  {
    id: 19,
    name: 'Samsung kietas dėklas "Fundamental"',
    price: "€9.00",
    color: "black",
    stock: 6,
    descriptions: [
      "Kietas dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: [
      "Samsung Galaxy A22",
      "Samsung Galaxy S21",
      "Samsung Galaxy S20",
      "Samsung Galaxy A12",
    ],
    image: "./phone3.jpg",
  },
  {
    id: 20,
    name: 'iPhone kietas dėklas "Gyvenimas"',
    stock: 2,
    price: "€9.00",
    color: "white",
    descriptions: [
      "Kietas dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone4.jpg",
  },

  {
    id: 21,
    name: 'Samsung kietas dėklas "Mėnulis"',
    price: "€9.00",
    color: "black",
    stock: 4,
    descriptions: [
      "Kietas dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: [
      "Samsung Galaxy A22",
      "Samsung Galaxy S21",
      "Samsung Galaxy S20",
      "Samsung Galaxy A12",
    ],
    image: "./phone6.jpg",
  },
  {
    id: 22,
    name: 'iPhone guminis dėklas "Mėnulis"',
    price: "€8.00",
    color: "black",
    stock: 5,
    descriptions: [
      "Lankstus, guminis dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone7.jpg",
  },
  {
    id: 23,
    name: 'iPhone guminis dėklas "Fundamental"',
    stock: 2,
    price: "€8.00",
    color: "black",
    descriptions: [
      "Lankstus, guminis dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone8.jpg",
  },
  {
    id: 24,
    stock: 1,
    name: 'iPhone guminis dėklas "Briedis"',
    price: "€8.00",
    color: "black",
    descriptions: [
      "Lankstus, guminis dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone9.jpg",
  },
];
