export const clothes = [
  {
    id: 1,
    name: 'Prailginti marškinėliai "Fundamental"',
    stock: 3,
    price: "€18.00",
    color: "white",
    descriptions: [
      "Prailginti vienspalviai marškinėliai su užapvalinta nugara apačioje",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["XS", "L", "XL"],
    image: "./1.jpg",
  },
  {
    id: 2,
    name: 'Klasikiniai marškinėliai "Fundamental"',
    stock: 1,
    price: "€16.00",
    color: "black",
    descriptions: [
      "Klasikinio stiliaus, tiesaus kirpimo marškinėliai trumpomis rankovėmis su apvalia apykakle",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["S", "XS", "L", "XL"],
    image: "./2.jpg",
  },
  {
    id: 3,
    name: 'Džemperis "Fundamental"',
    stock: 5,
    price: "€35.00",
    color: "grey",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["XS", "M", "XL"],
    image: "./3.jpg",
  },
  {
    id: 4,
    name: 'Džemperis "Fundamental"',
    stock: 6,
    price: "€35.00",
    color: "black",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["XS", "L", "M", "XL"],
    image: "./4.jpg",
  },

  {
    id: 5,
    name: 'Prailginti marškinėliai "Gyvenimas"',
    stock: 4,
    price: "€18.00",
    color: "white",
    descriptions: [
      "Prailginti vienspalviai marškinėliai su užapvalinta nugara apačioje",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["M", "L"],
    image: "./6.jpg",
  },
  {
    id: 6,
    name: 'Džemperis "Gyvenimas"',
    stock: 2,
    price: "€35.00",
    color: "white",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["XS", "L", "M", "XL"],
    image: "./7.jpg",
  },
  {
    id: 7,
    name: 'Prailginti marškinėliai "Gyvenimas"',
    stock: 1,
    price: "€18.00",
    color: "black",
    descriptions: [
      "Prailginti vienspalviai marškinėliai su užapvalinta nugara apačioje",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["S", "M", "L"],
    image: "./8.jpg",
  },
  {
    id: 8,
    stock: 7,
    name: 'Džemperis "Gyvenimas"',
    price: "€35.00",
    color: "black",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["XS", "M", "L", "XL"],
    image: "./9.jpg",
  },
  {
    id: 9,
    stock: 9,
    name: 'Džemperis "Medis"',
    price: "€35.00",
    color: "blue",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["M", "XL", "XXL"],
    image: "./18.jpg",
  },
  {
    id: 10,
    stock: 7,
    name: 'Džemperis "Briedis"',
    price: "€35.00",
    color: "black",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["S", "M", "L", "XL"],
    image: "./11.jpg",
  },
  {
    id: 11,
    stock: 2,
    name: 'Džemperis "Briedis"',
    price: "€35.00",
    color: "black",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["S", "M", "L", "XL"],
    image: "./12.jpg",
  },
  {
    id: 12,
    stock: 4,
    name: 'Suknelė "Briedis"',
    price: "€30.00",
    color: "black",
    descriptions: [
      "Lenktos formos srauni suknelė, suteikianti lengvumo pojūtį ",
      "97% poliesteris 3% elastanas ",
    ],
    sizes: ["XS", "S"],
    image: "./13.jpg",
  },
  {
    id: 13,
    stock: 5,
    name: 'Prailginti marškinėliai "Briedis"',
    price: "€18.00",
    color: "white",
    descriptions: [
      "Prailginti vienspalviai marškinėliai su užapvalinta nugara apačioje",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["L", "XXL"],
    image: "./14.jpg",
  },
  {
    id: 14,
    stock: 8,
    name: 'Džemperis "Briedis"',
    price: "€35.00",
    color: "grey",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["S", "XL", "XXL"],
    image: "./15.jpg",
  },
  {
    id: 15,
    stock: 7,
    name: 'Suknelė "Briedis"',
    price: "€30.00",
    color: "black",
    descriptions: [
      "Lenktos formos srauni suknelė, suteikianti lengvumo pojūtį ",
      "97% poliesteris 3% elastanas ",
    ],
    sizes: ["XS", "S", "M"],
    image: "./17.jpg",
  },
  {
    id: 16,
    stock: 2,
    name: 'Klasikiniai marškinėliai "Medis"',
    price: "€16.00",
    color: "black",
    descriptions: [
      "Klasikinio stiliaus, tiesaus kirpimo marškinėliai trumpomis rankovėmis su apvalia apykakle",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["XS", "L", "XL"],
    image: "./16.jpg",
  },
];
