export const SearchData = [
  {
    id: 1,
    name: 'Prailginti marškinėliai "Fundamental"',
    price: "€18.00",
    color: "white",
    descriptions: [
      "Prailginti vienspalviai marškinėliai su užapvalinta nugara apačioje",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["XS", "L", "XL"],
    image: "./1.jpg",
  },
  {
    id: 2,
    name: 'Klasikiniai marškinėliai "Fundamental"',
    price: "€16.00",
    color: "black",
    descriptions: [
      "Klasikinio stiliaus, tiesaus kirpimo marškinėliai trumpomis rankovėmis su apvalia apykakle",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["S", "XS", "L", "XL"],
    image: "./2.jpg",
  },
  {
    id: 3,
    name: 'Džemperis "Fundamental"',
    price: "€35.00",
    color: "grey",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["XS", "M", "XL"],
    image: "./3.jpg",
  },
  {
    id: 4,
    name: 'Džemperis "Fundamental"',
    price: "€35.00",
    color: "black",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["XS", "L", "M", "XL"],
    image: "./4.jpg",
  },

  {
    id: 5,
    name: 'Prailginti marškinėliai "Gyvenimas"',
    price: "€18.00",
    color: "white",
    descriptions: [
      "Prailginti vienspalviai marškinėliai su užapvalinta nugara apačioje",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["M", "L"],
    image: "./6.jpg",
  },
  {
    id: 6,
    name: 'Džemperis "Gyvenimas"',
    price: "€35.00",
    color: "white",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["XS", "L", "M", "XL"],
    image: "./7.jpg",
  },
  {
    id: 7,
    name: 'Prailginti marškinėliai "Gyvenimas"',
    price: "€18.00",
    color: "black",
    descriptions: [
      "Prailginti vienspalviai marškinėliai su užapvalinta nugara apačioje",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["S", "M", "L"],
    image: "./8.jpg",
  },
  {
    id: 8,
    name: 'Džemperis "Gyvenimas"',
    price: "€35.00",
    color: "black",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["XS", "M", "L", "XL"],
    image: "./9.jpg",
  },
  {
    id: 9,
    name: 'Džemperis "Medis"',
    price: "€35.00",
    color: "blue",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["M", "XL", "XXL"],
    image: "./18.jpg",
  },
  {
    id: 10,
    name: 'Džemperis "Briedis"',
    price: "€35.00",
    color: "black",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["S", "M", "L", "XL"],
    image: "./11.jpg",
  },
  {
    id: 11,
    name: 'Džemperis "Briedis"',
    price: "€35.00",
    color: "black",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["S", "M", "L", "XL"],
    image: "./12.jpg",
  },
  {
    id: 12,
    name: 'Suknelė "Briedis"',
    price: "€30.00",
    color: "black",
    descriptions: [
      "Lenktos formos srauni suknelė, suteikianti lengvumo pojūtį ",
      "97% poliesteris 3% elastanas ",
    ],
    sizes: ["XS", "S"],
    image: "./13.jpg",
  },
  {
    id: 13,
    name: 'Prailginti marškinėliai "Briedis"',
    price: "€18.00",
    color: "white",
    descriptions: [
      "Prailginti vienspalviai marškinėliai su užapvalinta nugara apačioje",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["L", "XXL"],
    image: "./14.jpg",
  },
  {
    id: 14,
    name: 'Džemperis "Briedis"',
    price: "€35.00",
    color: "grey",
    descriptions: [
      "Laisvalaikio stiliaus džemperis su gobtuvu ir uždėtine kišene ant priekio detalės",
      "80% medvilnė ir 20% polisteris",
    ],
    sizes: ["S", "XL", "XXL"],
    image: "./15.jpg",
  },
  {
    id: 15,
    name: 'Suknelė "Briedis"',
    price: "€30.00",
    color: "black",
    descriptions: [
      "Lenktos formos srauni suknelė, suteikianti lengvumo pojūtį ",
      "97% poliesteris 3% elastanas ",
    ],
    sizes: ["XS", "S", "M"],
    image: "./17.jpg",
  },
  {
    id: 16,
    name: 'Klasikiniai marškinėliai "Medis"',
    price: "€16.00",
    color: "black",
    descriptions: [
      "Klasikinio stiliaus, tiesaus kirpimo marškinėliai trumpomis rankovėmis su apvalia apykakle",
      "100% šukuotinė medvilnė",
    ],
    sizes: ["XS", "L", "XL"],
    image: "./16.jpg",
  },
  {
    id: 17,
    prevId: 1,
    name: 'iPhone guminis dėklas "Fundamental"',
    price: "€8.00",
    color: "black",
    descriptions: [
      "Lankstus, guminis dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone1.jpg",
  },
  {
    id: 18,
    prevId: 2,
    name: 'iPhone kietas dėklas "Fundamental"',
    price: "€9.00",
    color: "black",
    descriptions: [
      "Kietas dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone2.jpg",
  },
  {
    id: 19,
    prevId: 3,
    name: 'Samsung kietas dėklas "Fundamental"',
    price: "€9.00",
    color: "black",
    descriptions: [
      "Kietas dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: [
      "Samsung Galaxy A22",
      "Samsung Galaxy S21",
      "Samsung Galaxy S20",
      "Samsung Galaxy A12",
    ],
    image: "./phone3.jpg",
  },
  {
    id: 20,
    prevId: 4,
    name: 'iPhone kietas dėklas "Gyvenimas"',
    price: "€9.00",
    color: "white",
    descriptions: [
      "Kietas dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone4.jpg",
  },

  {
    id: 21,
    prevId: 5,
    name: 'Samsung kietas dėklas "Mėnulis"',
    price: "€9.00",
    color: "black",
    descriptions: [
      "Kietas dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: [
      "Samsung Galaxy A22",
      "Samsung Galaxy S21",
      "Samsung Galaxy S20",
      "Samsung Galaxy A12",
    ],
    image: "./phone6.jpg",
  },
  {
    id: 22,
    prevId: 6,
    name: 'iPhone guminis dėklas "Mėnulis"',
    price: "€8.00",
    color: "black",
    descriptions: [
      "Lankstus, guminis dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone7.jpg",
  },
  {
    id: 23,
    prevId: 7,
    name: 'iPhone guminis dėklas "Fundamental"',
    price: "€8.00",
    color: "black",
    descriptions: [
      "Lankstus, guminis dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone8.jpg",
  },
  {
    id: 24,
    prevId: 8,
    name: 'iPhone guminis dėklas "Briedis"',
    price: "€8.00",
    color: "black",
    descriptions: [
      "Lankstus, guminis dėklas, kuris apgaubia telefono kraštus, taip apsaugodamas nuo dūžių",
      "Dėkle panaudota pirštų antspaudams atspari technologija",
      "Svoris 26g",
      "Storis 1.6mm",
      "Tinkamas bevieliam įkrovimui",
    ],
    models: ["iPhone 12", "iPhone 11", "iPhone XS", "iPhone XR"],
    image: "./phone9.jpg",
  },
];
